version: 2
updates:
  # Enable version updates for dependencies
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates daily
    schedule:
      interval: "daily"
    # Labels on pull requests for version updates only
    labels: 
      - "pip dependencies"
